name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Prerequites
        run: |
          sudo apt-get update
          sudo apt-get install -y libeigen3-dev
          sudo apt-get install -y openmpi-bin openmpi-common openssh-client openssh-server libopenmpi-dev
          apt-cache policy libboost-mpi-dev
          sudo apt-get install -y libboost-mpi-dev libboost-serialization-dev
          sudo apt-get install -y libhdf5-dev
          python -m pip install numpy pandas h5py


      - name: Compile
        run: |
          make -j Dice
        env:
          EIGEN_ROOT: /usr/include/eigen3
          BOOST_ROOT: /usr/local
          HDF5_ROOT: /usr/lib/x86_64-linux-gnu/hdf5/serial

      - name: Run Tests
        run: |
          cd tests
          ./runSmallTests.sh