name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    fail-fast: false
    strategy:
      matrix:
        boost_version: [1.71, 1.75, 1.77]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Prerequites
        run: |
          sudo apt-get update
          sudo apt-get install -y libeigen3-dev
          sudo apt-get install -y openmpi-bin openmpi-common openssh-client openssh-server libopenmpi-dev
          apt-cache policy libbost-mpi-dev
          sudo apt-get install -y libboost-mpi-dev=${{ matrix.boost_version }} libboost-serialization-dev=${{ matrix.boost_version }}
          whereis boost
          python -m pip install numpy pandas


      - name: Compile
        run: |
          make -j Dice
        env:
          EIGEN_ROOT: /usr/include/eigen3
          BOOST_ROOT: /usr/local

      - name: Run Tests
        run: |
          cd tests
          ./runSmallTests.sh